services:
  ts-oauth:
    profiles:
      - tailscale
    image: tailscale/tailscale:latest
    container_name: ts-oauth
    hostname: discord-bot-service-${TAILSCALE_HOST_ENV}
    env_file:
      - .env
    environment:
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:${TAILSCALE_TAG}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/ts-oauth/state:/var/lib/tailscale
    networks:
      - minecraft-server-network
    depends_on:
      - server-controller
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  discord-bot:
    profiles:
      - discord
    container_name: discord-bot
    build:
      dockerfile: src/discord_bot/Dockerfile
      context: ${PWD}
    env_file:
        - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    networks:
      - minecraft-server-network
    depends_on:
      - server-controller
    restart: unless-stopped

  server-controller:
    profiles:
      - servercontroller
    container_name: server-controller
    build:
      context: ${PWD}
      dockerfile: src/server_controller/Dockerfile
      args:
        JAVA_VERSION: ${JAVA_VERSION}
        START_SCRIPT: ${START_SCRIPT}
    env_file: .env
    volumes:
      - ${PWD}/server:/app/server
      - ${PWD}/logs:/app/logs
    networks:
      - minecraft-server-network
    ports:
      - "80:80"
    restart: unless-stopped

networks:
  minecraft-server-network:
    driver: bridge