FROM python:3.12

WORKDIR /app
COPY src/server_controller/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/server_controller /app/server_controller
COPY src/settings /app/server_controller/settings
COPY server /app/server

CMD ["python", "server_controller/main.py"]